### ISSUE TITLE
learn_params_em() for empty node

### ISSUE THREAD

**Issue by shihui2010** [bayesnet/bnt#45]
Hi, 
I'm trying to estimate parameter for a Bayesian Network by function learn_params_em(). The variables in the network are either partially observed, or purely have no observation at all. I found the brief documentation of this function in the link below:
http://bnt.googlecode.com/svn/trunk/docs/usage.html

I see it says learn_params_em() is for conditions "when some values are not observed". My question is when "all values are not observed", will this function return meaningful results?

Thanks,

**Comment by Ionhihir** [comment]
Dear Shihui, 

You're right, no need to keep empty samples. 
As well as strongly unobserved entries, more than 66% missing attributes. 

But when the missing rate is low (below 30%) 
the results is smotther than with only fully observed entries, with is a good thing. 

Olivier FRANÇOIS 
01 81 66 87 23 
COSYS / GRETTIA

**Comment by shihui2010** [comment]
Thank you so much for reply.
I see even I feed the function with variables that have no observation, it can still estimate a distribution of the variables. Just out of curiosity, is such distribution reliable? And if so, how can I interpret the estimation.

**Comment by Ionhihir** [comment]
Hi, 

as I said :"You're right, no need to keep empty samples." 

Nethertheless if you add empty sample it does't change de results as if there was not there. 
Just have a look at a simple EM algorithm run to understand it. 

Regards. 

Olivier FRANÇOIS 
01 81 66 87 23 
COSYS / GRETTIA

**Comment by shihui2010** [comment]
Hi,

I strongly agree that "adding empty samples doesn't change the results as they are not present". 

However, just to make my question clearer. If I add an empty node into network, the function I'm asking will output a distribution of this empty node. Specifically, I want to know if the distribution of this empty node is reliable or not.

Thanks,

**Comment by Ionhihir** [comment]
Hi, 

Of course, this method is usually named adding a latent variable. 
The difficulties is to find the good size of this variable. 
Main response to this is to use an information criterion (as BIC). 

Then when performing learning with EM, you will get a very pertinent node which is usually used in architecture as 
- Hierarchical latent class classifier 
for instance. 
This is a mainly used for unsupervised learning. 

Olivier FRANÇOIS 
01 81 66 87 23 
COSYS / GRETTIA

**Comment by shihui2010** [comment]
Okay, I got your point.
Thank you so much for clarifying. It's quite helpful.
